apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hi-deployer-
  namespace: default
spec:
  params:
    - name: name
      value: deployer-world
  pipelineRef:
    name: hi-deployer
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 8h0m0s
